version: 2

sources:
  - name: fivetran
    database: fivetran-494113
    schema: logistics
    tables:
      - name: student_jeanne_eichelbrenner_entrepot_zone_temperature
      - name: student_jeanne_eichelbrenner_entrepot_zone_mouvements
      - name: student_jeanne_eichelbrenner_entrepot_zone_anomalies