version: 2

sources:
  - name: vtc
    description: "Les données brutes de l'entreprise VTC Paris."
    database: vtc-paris-493907
    schema: modele_en_etoile
    tables:
      - name: clients
        description: "Table des clients, contenant les informations démographiques et de segment."
      - name: trajets
        description: "Table des trajets avec les informations sur les trajets effectués, y compris les montants et distances."
      - name: vehicules
        description: "Table des véhicules avec les informations sur le modèle et le type de véhicule."
      - name: dates
        description: "Table des dates avec les informations sur le jour, le mois, l'année et le trimestre du vehicule."
